name: Build and Release ShiroAttack2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # 使用 Eclipse Temurin JDK（兼容 Liberica）
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4  # ✅ 更新到 v4
        with:
          name: ShiroAttack2-JAR
          path: target/shiro_attack-4.5.6-SNAPSHOT-all.jar

      - name: Release JAR (on new tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: target/shiro_attack-4.5.6-SNAPSHOT-all.jar
